services:
  db: 
    image: mysql:5.7
    container_name: banco
    restart: always
    environment: 
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: appuser
      MYSQL-PASSWORD: apppasword
      MYSQL_ ROOT_PASSWORD: rootpass
    ports: 
      - 3306:3306